app/player/__init__.py
from flask import Blueprint

player = Blueprint("player", __name__)

from . import views

app/player/views.py
from flask import render_template, redirect, request, flash, make_response, Markup
from flask_babel import lazy_gettext as _l
from flask_login import current_user
from . import player
from .. import babel
from ..models import MasterAccount, Waypoint, QrCode, Person, Playgroup
import datetime
import uuid
from dotenv import load_dotenv
import os

load_dotenv()

QR_CODE_BASE_URL = '{}://{}{}'.format(os.getenv('PREFERRED_URL_SCHEME'), os.getenv('SERVER_NAME'), os.getenv('APP_ROOT'))


#
# Locale Initialization
#

@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(os.getenv('LANGUAGES').split(','))

#
# Routes
#


@player.route("/", methods=["GET"])
def index():
    """
    Displays a progress overview for known players
    and a generic welcome page for everyone else.
    """
    if "player_uuid" in request.cookies:
        # we should know this player! because usually we set the cookie ourselves
        player_uuid = request.cookies.get("player_uuid")
        
        try:
            # get the person from db
            person = Person.objects.get(uuid=player_uuid)
        except Person.DoesNotExist:
            flash(_l("Invalid player data. Removing your session cookie."))
            response = make_response(render_template("/player/index.html"))
            response.set_cookie("player_uuid", "", expires=0)
            return response
        
        # get the associated playgroup
        playgroup = person.playgroup.fetch()
        # get the track belonging to the playgroup
        track = playgroup.track.fetch()

        # get all waypoints of the track
        waypoints = Waypoint.objects(track=track)
        waypoint_objs = []
        # aggregate them with all important information
        waypoint_objs = list(map(lambda x: create_waypoint_object(track=track, playgroup=playgroup, waypoint=next(filter(lambda y: y.station == x, waypoints))), track.stations))

        # hint handling
        next_station_hint = ""
        next_station = get_next_station(playgroup)
        if next_station is not None:
            next_station = next_station.fetch()
            if next_station.hint is not None:
                next_station_hint = next_station.hint
        else:
            next_station_hint = _l("Congratulations! You made it to the end!")

        # show the progress!
        return render_template("/player/progress.html",
                                track_name=track.name,
                                waypoints=waypoint_objs,
                                display_hint=playgroup.solved_current_challenge or next_station is None or next_station.challenge is None,
                                next_station_hint=next_station_hint)

    # just show the index page
    return render_template("/player/index.html")


@player.route("/waypoint/<qr_code>", methods=["GET", "POST"])
def waypoint(qr_code):
    """
    Entry for all scanned QR codes. Checks whether the waypoint is already
    discovered and displays the station description or an error otherwise.
    
    Sets up unknown devices as new players in the corresponding playgroup if a
    waypoint which is first in its track is scanned.
    """
    try:
        qr_code = QrCode.objects.get(code=qr_code)
    except QrCode.DoesNotExist:
        flash(_l("Invalid waypoint."))
        return redirect("/")

    # the waypoint marked by the scanned qr code
    waypoint = Waypoint.objects.get(qr_code=qr_code)
    # the station associated with the waypoint
    station = waypoint.station.fetch()
    # the track which the waypoint belongs to
    track = waypoint.track.fetch()
    # the playgroup owning the track which the waypoint belongs to
    playgroup = Playgroup.objects.get(track=waypoint.track.fetch())
    waypoint_object = create_waypoint_object(waypoint=waypoint, track=track, playgroup=playgroup)

    # for each waypoint, find the index of the associated station in this track
    visited_idxs = map(lambda x: track.stations.index(x.fetch().station), playgroup.visited_waypoints)
    # progress is the max station index we visited
    progress = max(visited_idxs, default=0)
    # position is the index of this station
    position = track.stations.index(station)

    waypoints = []
    # all waypoints of the track
    waypoints = Waypoint.objects(track=track)
    waypoint_objs = list(map(lambda x: create_waypoint_object(track=track, playgroup=playgroup, waypoint=next(filter(lambda y: y.station == x, waypoints))), track.stations))

    if playgroup is None:
        flash(_l("An error occured. Please ask an FSR-I member to set up the corresponding playgroup."))
        return redirect("/")

    # hint handling
    next_station_hint = ""
    next_station = get_next_station(playgroup)
    if next_station is not None:
        next_station = next_station.fetch()
        if next_station.hint is not None:
            next_station_hint = next_station.hint
    else:
        next_station_hint = _l("Congratulations! You made it to the end!")

    # whether a master account is signed in
    is_master = False
    if current_user is not None:
        if current_user.get_id() is not None:
            user = MasterAccount.objects.with_id(current_user.get_id())
            if user is not None:
                is_master = user.is_authenticated
            else:
                flash(_l("Research suggests you don't exist!"))

    if is_master:
        # master wants to look at the track, we don't need to do anything else
        flash(_l("You are viewing this as master. No modifications will be made."))
        flash(Markup('{} {}'.format(_l("Next station:"), next_station_hint)))
    elif position == 0 and "player_uuid" not in request.cookies:
        # new player, who dis?
        response = make_response(render_template("/player/waypoint.html",
                                                track_name=track.name,
                                                waypoints=waypoint_objs,
                                                station_name=station.name,
                                                station_content=station.content,
                                                has_challenge=station.challenge is not None,
                                                is_master=is_master,
                                                next_station_hint=next_station_hint))

        # create a new uuid
        player_uuid = str(uuid.uuid4())

        try:
            # add the player to the db
            person = Person(uuid=player_uuid, playgroup=playgroup)
            person.save()
            if waypoint not in playgroup.visited_waypoints:
                playgroup.visited_waypoints.append(waypoint)
                playgroup.save()
            #db.session.commit()
        except:
            import traceback
            traceback.print_exc()
            #db.session.rollback()
            flash(_l("An error occured while attempting to register your device with the server."))
            return redirect("/")

        # set cookie. valid for 12 hours
        expire_date = datetime.datetime.now() + datetime.timedelta(hours=12)
        response.set_cookie("player_uuid", player_uuid, expires=expire_date)

        return response
    elif position >= 0 and "player_uuid" in request.cookies:
        player_uuid = request.cookies.get("player_uuid")
        # the player
        try:
            person = Person.objects.get(uuid=player_uuid)
        except Person.DoesNotExist:
            # known player, later waypoint
            flash(_l("Invalid player data. Removing your session cookie."))
            response = redirect("/")
            response.set_cookie("player_uuid", "", expires=0)
            return response
        
        if person.playgroup.fetch() != playgroup:
            flash(_l("You're in a different track/playgroup."))
            return redirect("/")

        if position > progress + 1:
            # waypoint is not yet reachable
            flash(_l("You're not allowed to visit this waypoint."))
            return redirect("/")

        if waypoint not in playgroup.visited_waypoints:
            try:
                playgroup.visited_waypoints.append(waypoint)
                playgroup.solved_current_challenge = False
                playgroup.save()
                #db.session.commit()
            except:
                #db.session.rollback()
                flash(_l("An error occured while attempting to save your game progress."))
                return redirect("/")
    else:
        if position > progress:
            flash(_l("You're not allowed to visit this waypoint."))
            return redirect("/")

    return render_template("/player/waypoint.html",
                           track_name=track.name,
                           waypoints=waypoint_objs,
                           station_name=station.name,
                           station_content=station.content,
                           has_challenge=station.challenge is not None,
                           is_master=is_master,
                           next_station_hint=next_station_hint)


@player.route("/waypoint/<qr_code>/challenge", methods=["GET", "POST"])
def challenge(qr_code):
    # whether a master account is signed in
    is_master = False
    if current_user.get_id() is not None:
        user = MasterAccount.objects.with_id(current_user.get_id())
        if user is not None:
            is_master = user.is_authenticated

    if "player_uuid" not in request.cookies and not is_master:
        flash(_l("You're not allowed to try this challenge."))
        return redirect("/waypoint/{}".format(qr_code))

    try:
        qr_code = QrCode.objects.get(code=qr_code)
    except QrCode.DoesNotExist:
        flash(_l("Invalid waypoint."))
        return redirect("/")

    # the waypoint marked by the scanned qr code
    waypoint = Waypoint.objects.get(qr_code=qr_code)
    # the station associated with the waypoint
    station = waypoint.station.fetch()

app/templates/player/challenge.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='css/summernote/summernote.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/summernote.min.js') }}"></script>

        <title>{{ challenge.name }}</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('player.index') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            <h2>{{ _("Your Track") }}: {{ track_name }}</h2>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="summernote">
                {{ challenge.content|safe }}
            </div>

            {% if solved %}
            <form method="POST">
                <div class="button right">
                    <input name="skip_btn" type="submit" value="{{ _('Skip') }}"/>
                </div>
            </form>

            <div class="summernote">
                {{ next_station_hint|safe }}
            </div>
            {% endif %}
              
        </div>
    </body>
</html>

app/templates/player/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>QRitzeljagd</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="">
                    <div class="qritzeljagd-font"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="info">
                <h1>{{ _("Welcome to QRitzeljagd!") }}</h1>
                <h2>{{ _("This little game will tour you around our small but beautiful university campus. We wish you much success!") }}</h2>

                <div class="intro">
                    <div class="first"></div>
                    <div class="second"></div>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/player/progress.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>QRitzeljagd</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="">
                    <div class="qritzeljagd-font"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="info">
                <h1>{{ _("Your progress") }}</h1>
                <h2>{{ _("Your Track") }}: {{ track_name }}</h2>

                <div class="progressbar">
                    {% for waypoint in waypoints %}
                    {% if waypoint.found %}
                    <a href="{{ waypoint.url }}">
                        <div class="waypoint found">
                            {{ waypoint.position }}
                        </div>
                    </a>
                    {% else %}
                    <a href="#">
                        <div class="waypoint">
                            {{ waypoint.position }}
                        </div>
                    </a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>

            {% if display_hint %}
            <div class="summernote">
                <h3>{{ _("Next station:") }}</h3>
                {{ next_station_hint|safe }}
            </div>
            {% endif %}

            <div class="spacer"></div>
        </div>
    </body>
</html>

app/templates/player/waypoint.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='css/summernote/summernote.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/summernote.min.js') }}"></script>

        <title>{{ station_name }}</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('player.index') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            <h2>{{ _("Your Track") }}: {{ track_name }}</h2>

            <div class="progressbar">
                {% for waypoint in waypoints %}
                {% if waypoint.found or is_master %}
                <a href="{{ waypoint.url }}">
                {% else %}
                <a href="#">
                {% endif %}
                    {% if waypoint.station.name == station_name %}
                    <div class="waypoint current">
                    {% elif waypoint.found %}
                    <div class="waypoint found">
                    {% else %}
                    <div class="waypoint">
                    {% endif %}
                        {{ loop.index }}
                    </div>
                </a>
                {% endfor %}
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="summernote">
                {{ station_content|safe }}
            </div>

            {% if has_challenge %}
            <a class="button" href="{{ request.path }}/challenge">{{ _("To The Challenge!") }}</a>
            {% else %}
            <div class="divider horizontal"></div>
            <div>
                <h3>{{ _("Next station:") }}</h3>
                {{ next_station_hint|safe }}
            </div>
            {% endif %}
              
        </div>
    </body>
</html>