app/master/__init__.py
from flask import Blueprint

master = Blueprint("master", __name__)

from . import views

app/master/views.py
from flask import Flask, render_template, redirect, request, flash
from flask_babel import lazy_gettext as _l
from flask_login import current_user, login_user, login_required, logout_user
from flask_weasyprint import HTML, render_pdf
from . import master
from ..models import MasterAccount, Station, Challenge, Track, Waypoint, QrCode, Playgroup, Person, Printout
from .. import login_manager
import hashlib
import random
from dotenv import load_dotenv
import os

load_dotenv()

QR_CODE_BASE_URL = '{}://{}{}'.format(os.getenv('PREFERRED_URL_SCHEME'), os.getenv('SERVER_NAME'), os.getenv('APP_ROOT'))


#
# Routes
#

@master.route("/master", methods=["GET"])
def index():
    return redirect("/master/login")

@master.route("/master/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect("/master/overview")
    
    if "login_btn" in request.form and request.method == "POST":
        input_username = request.form["username"]
        input_password = request.form["password"]

        try:
            user = MasterAccount.objects.get(username=input_username)
            if user.check_password(input_password) is True:
                login_user(user)
                next = request.args.get("next")
                return redirect(next or "/master/overview")
        except MasterAccount.DoesNotExist:
            pass

        flash(_l("Wrong credentials."))

    return render_template("/master/login.html")

@master.route("/master/overview", methods=["GET", "POST"])
@login_required
def overview():
    return render_template("/master/overview.html")

@master.route("/master/stations", methods=["GET", "POST"])
@login_required
def stations():
    boxes = Station.objects.all()
    for box in boxes:
        box.info = box.location

    return render_template("/master/stations.html",
                           boxes=boxes)

@master.route("/master/stations/add", methods=["GET", "POST"])
@login_required
def stations_add():
    #challenge_choices = Challenge.objects.all()
    challenge_choices = list(map(lambda x: x.name, Challenge.objects))
    # add an option for no playgroup at all
    challenge_choices.insert(0, "")
    preselect = ""

    if "cancel_btn" in request.form and request.method == "POST":
        return redirect("/master/stations")
    elif "save_btn" in request.form and request.method == "POST":
        input_name = request.form["name"]
        input_location = request.form["location"]
        input_content = request.form["content"]
        input_hint = request.form["hint"]
        select_challenge = request.form["select_challenge"]

        if input_name == "" or input_location == "" or input_content == "":
            flash(_l("Please fill out all forms."))
            return render_template("/master/stations_edit.html",
                                   value_name=input_name,
                                   value_info=input_location,
                                   value_content=input_content,
                                   value_hint=input_hint,
                                   challenge_choices=challenge_choices,
                                   preselect=select_challenge,
                                   editing=False)

        challenge = None
        if select_challenge != "":
            for challenge_pick in Challenge.objects:
                if challenge_pick.name == select_challenge:
                    challenge = challenge_pick
                    break

        try:
            Station(name=input_name,
                    location=input_location,
                    content=input_content,
                    hint=input_hint,
                    challenge=challenge).save()
        except IntegrityError:
            #db.session.rollback()
            flash(_l("Station with this name already exists."))
            return render_template("/master/stations_edit.html",
                                   value_name=input_name,
                                   value_info=input_location,
                                   value_content=input_content,
                                   value_hint=input_hint,
                                   challenge_choices=challenge_choices,
                                   preselect=select_challenge,
                                   editing=False)
        except DataError:
            #db.session.rollback()
            flash(_l("Data error occured. Check the values for compatibility with the data types in the database."))
            return render_template("/master/stations_edit.html",
                                   value_name=input_name,
                                   value_info=input_location,
                                   value_content=input_content,
                                   value_hint=input_hint,
                                   challenge_choices=challenge_choices,
                                   preselect=select_challenge,
                                   editing=False)
        except:
            #db.session.rollback()
            flash(_l("An error occured."))
        
        return redirect("/master/stations")

    return render_template("/master/stations_edit.html",
                           value_name="",
                           value_info="",
                           value_content="",
                           value_hint="",
                           challenge_choices=challenge_choices,
                           preselect="",
                           editing=False)

@master.route("/master/stations/<station_id>", methods=["GET", "POST"])
@login_required
def stations_show(station_id):
    station = Station.objects.with_id(station_id)
    if not station.challenge:
        preselect = ""
    else:
        preselect = station.challenge.fetch().name

    challenge_choices = Challenge.objects.all()
    challenge_choices = list(map(lambda x: x.name, challenge_choices))
    # add an option for no playgroup at all
    challenge_choices.insert(0, "")

    input_hint = station.hint
    if input_hint is None:
        input_hint = ""

    if station is None:
        flash(_l("Invalid Station."))
        return redirect("/master/stations")
    
    if "cancel_btn" in request.form and request.method == "POST":
        return redirect("/master/stations")
    elif "delete_btn" in request.form and request.method == "POST":
        try:
            for track in Track.objects(stations=station):
                track.stations.remove(station)
                track.save()

            for waypoint in Waypoint.objects(station=station):
                waypoint.qr_code.delete()
                waypoint.delete()

            station.delete()
            flash(_l("Station deleted."))
        except:
            #db.session.rollback()
            flash(_l("Error while deleting station."))

        return redirect("/master/stations")
    elif "save_btn" in request.form and request.method == "POST":
        input_name = request.form["name"]
        input_location = request.form["location"]
        input_content = request.form["content"]
        input_hint = request.form["hint"]
        select_challenge = request.form["select_challenge"]

        if input_name == "" or input_location == "" or input_content == "":
            flash(_l("Please fill out all forms."))
            return render_template("/master/stations_edit.html",
                                   value_name=input_name,
                                   value_info=input_location,
                                   value_content=input_content,
                                   value_hint=input_hint,
                                   challenge_choices=challenge_choices,
                                   preselect=select_challenge,
                                   editing=True)

        if select_challenge != "":
            challenge = Challenge.objects.get(name=select_challenge)
        else:
            challenge = None

        try:
            station.name = input_name
            station.location = input_location
            station.content = input_content
            station.hint = input_hint
            station.challenge = challenge

            station.save()
        except DataError:
            #db.session.rollback()
            flash(_l("Data error occured. Check the values for compatibility with the data types in the database."))
            return render_template("/master/stations_edit.html",
                                   value_name=input_name,
                                   value_info=input_location,
                                   value_content=input_content,
                                   value_hint=input_hint,
                                   challenge_choices=challenge_choices,
                                   preselect=select_challenge,
                                   editing=True)
        except:
            #db.session.rollback()
            flash(_l("An error occured."))
        
        return redirect("/master/stations")
    
    return render_template("/master/stations_edit.html",
                            value_name=station.name,
                            value_info=station.location,
                            value_content=station.content,
                            value_hint=input_hint,
                            challenge_choices=challenge_choices,
                            preselect=preselect,
                            editing=True)

@master.route("/master/challenges", methods=["GET", "POST"])
@login_required
def challenges():
    boxes = Challenge.objects.all()
    for box in boxes:
        box.info = box.description

    return render_template("/master/challenges.html",
                           boxes=boxes)

@master.route("/master/challenges/add", methods=["GET", "POST"])
@login_required
def challenges_add():
    if "cancel_btn" in request.form and request.method == "POST":
        return redirect("/master/challenges")

app/templates/master/challenges.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Challenges</title>
    </head>
    <body>

        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.challenges') }}">
                    <div class="dir name">
                        <p>Challenges</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="station-list-container">
                <div class="add">
                    <a href="{{ url_for('master.challenges_add') }}">
                        <div class="content">+</div>
                    </a>
                </div>
                {% for box in boxes %}
                <div class="station_box">
                    <a href="{{ url_for(request.endpoint) }}/{{ box.id }}">
                        <div class="content">
                            <div class="station_name">{{ box.name }}</div>
                            <div class="station_info">{{ box.info }}</div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>

app/templates/master/challenges_edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

        <!-- include libraries(jQuery, bootstrap) -->
        <link href="{{ url_for('static', filename='css/summernote/bootstrap.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/jquery-3.5.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/summernote/bootstrap.min.js') }}"></script>

        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='css/summernote/summernote.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/summernote.min.js') }}"></script>

        <title>Challenges</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.challenges') }}">
                    <div class="dir name">
                        <p>Challenges</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <form method="POST">
                <div class="box-padding left right bottom">
                    <p class="input-descriptor">{{ _("Name") }}</p>
                    <input type="text" name="name" value="{{ value_name }}"/>
                    <p class="input-descriptor">{{ _("Description") }}</p>
                    <input type="text" name="description" value="{{ value_info }}"/>
                    <p class="input-descriptor">{{ _("Challenge HTML") }}</p>
                    <textarea name="content" style="width: 100%; min-height: 25vh;">{{ value_content }}</textarea>
                    {% if editing %}
                    <p class="input-descriptor">{{ _("Delete Challenge") }}</p>
                    <div class="warning">
                        <input name="delete_btn" type="submit" value="{{ _('Delete') }}"/>
                    </div>
                    {% endif %}
                </div>

                <div class="divider horizontal"></div>

                <div class="button left">
                    <input name="cancel_btn" type="submit" value="{{ _('Cancel') }}"/>
                </div>

                <div class="button right">
                    <input name="save_btn" type="submit" value="{{ _('Save') }}"/>
                </div>
            </form>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>

app/templates/master/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Login</title>
    </head>
    <body>
        {% for message in get_flashed_messages() %}
        <div class="float-box">
          <div class="notification-box">
            <p>{{ message }}</p>
          </div>
        </div>
        {% endfor %}

        <div class="dialog-box login">
            <div class="box-padding all">
                <div class="qritzeljagd-logo medium"></div>
            </div>

            <form method="POST">
                <div class="box-padding left right bottom">
                    <p class="input-descriptor">{{ _("Username") }}</p>
                    <input type="text" name="username" value=""/>
                    <p class="input-descriptor">{{ _("Password") }}</p>
                    <input type="password" name="password" value=""/>
                </div>

                <input name="login_btn" type="submit" value="{{ _('Login') }}"/>
            </form>
        </div>
    </body>
</html>

app/templates/master/overview.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Overview</title>
    </head>
    <body>
        {% for message in get_flashed_messages() %}
        <div class="float-box">
          <div class="notification-box">
            <p>{{ message }}</p>
          </div>
        </div>
        {% endfor %}

        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            <div class="nav-box">
                <nav>
                    <ul>
                        <!--<li class="active"><a href="">{{ _("Overview") }}</a></li>-->
                        <li><a href="{{ url_for('master.stations') }}">{{ _("Stations") }}</a></li>
                        <li><a href="{{ url_for('master.challenges') }}">{{ _("Challenges") }}</a></li>
                        <li><a href="{{ url_for('master.tracks') }}">{{ _("Tracks") }}</a></li>
                        <li><a href="{{ url_for('master.playgroups') }}">{{ _("Playgroups") }}</a></li>
                        <li><a href="{{ url_for('master.printouts') }}">{{ _("Printouts") }}</a></li>
                    </ul>
                </nav>
            </div>

            <div class="spacer"></div>
        </div>
    </body>
</html>

app/templates/master/person_move.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

        <title>Move Person</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.playgroups') }}">
                    <div class="dir name">
                        <p>Playgroups</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <form method="POST">
                <div class="box-padding left right bottom">
                    <p class="input-descriptor">{{ _("UUID") }}</p>
                    <input type="text" name="uuid" value="{{ person.uuid }}" disabled/>

                    <p class="input-descriptor">{{ _("Note") }}</p>
                    <input type="text" name="note" value="{{ person.note }}"/>

                    <p class="input-descriptor">{{ _("Playgroup") }}</p>
                    <select name="select_playgroup">
                        {% for playgroup in playgroup_choices %}
                        {% if playgroup|string() == preselect|string() %}
                        <option value="{{ playgroup }}" selected>{{ playgroup }}</option>
                        {% else %}
                        <option value="{{ playgroup }}">{{ playgroup }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="divider horizontal"></div>

                <div class="button left">
                    <input name="cancel_btn" type="submit" value="{{ _('Cancel') }}"/>
                </div>

                <div class="button right">
                    <input name="save_btn" type="submit" value="{{ _('Save') }}"/>
                </div>
            </form>

            <div class="spacer"></div>

        </div>
    </body>
</html>

app/templates/master/playgroups.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Playgroups</title>
    </head>
    <body>

        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.playgroups') }}">
                    <div class="dir name">
                        <p>Playgroups</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="station-list-container">
                <div class="add">
                    <a href="{{ url_for('master.playgroups_add') }}">
                        <div class="content">+</div>
                    </a>
                </div>
                {% for box in boxes %}
                <div class="station_box">
                    <a href="{{ url_for(request.endpoint) }}/{{ box.playgroup_id }}">
                        <div class="content">
                            <div class="station_name">{{ box.track_name }}</div>
                            <div class="station_info">{{ box.info }}</div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>

app/templates/master/printouts.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Printouts</title>
    </head>
    <body>

        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.challenges') }}">
                    <div class="dir name">
                        <p>Printouts</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="station-list-container">
                <div class="add">
                    <a href="{{ url_for('master.printouts_add') }}">
                        <div class="content">+</div>
                    </a>
                </div>
                {% for box in boxes %}
                <div class="station_box">
                    <a href="{{ url_for(request.endpoint) }}/{{ box.id }}">
                        <div class="content">
                            <div class="station_name">{{ box.station.name }}</div>
                            <div class="station_info">{{ _("%(codes_number)s codes", codes_number=box.codes|length) }} | {{ box.note }}<br>{{ (_("up to date") if box.proper_print else _("minor issues")) if box.no_wrong_info else _("has wrong info") }}</div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>

app/templates/master/stations.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
        <title>Stations</title>
    </head>
    <body>

        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.stations') }}">
                    <div class="dir name">
                        <p>Stations</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <div class="station-list-container">
                <div class="add">
                    <a href="{{ url_for('master.stations_add') }}">
                        <div class="content">+</div>
                    </a>
                </div>
                {% for box in boxes %}
                <div class="station_box">
                    <a href="{{ url_for(request.endpoint) }}/{{ box.id }}">
                        <div class="content">
                            <div class="station_name">{{ box.name }}</div>
                            <div class="station_info">{{ box.info }}</div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>

app/templates/master/stations_edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>

        <!-- include libraries(jQuery, bootstrap) -->
        <link href="{{ url_for('static', filename='css/summernote/bootstrap.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/jquery-3.5.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/summernote/bootstrap.min.js') }}"></script>

        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='css/summernote/summernote.min.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/summernote/summernote.min.js') }}"></script>

        <title>Station</title>
    </head>
    <body>
        <div class="dialog-box content">
            <div class="logo-bar">
                <a href="{{ url_for('master.overview') }}">
                    <div class="qritzeljagd-font"></div>
                </a>
                <div class="dir layer">
                    <p>/</p>
                </div>

                <a href="{{ url_for('master.stations') }}">
                    <div class="dir name">
                        <p>Stations</p>
                    </div>
                </a>

                <a href="{{ url_for('master.logout') }}">
                    <div class="logout"></div>
                </a>
            </div>

            <div class="divider horizontal"></div>

            {% for message in get_flashed_messages() %}
            <div class="float-box">
              <div class="notification-box">
                <p>{{ message }}</p>
              </div>
            </div>
            {% endfor %}

            <form method="POST">
                <div class="box-padding left right bottom">
                    <p class="input-descriptor">{{ _("Name") }}</p>
                    <input type="text" name="name" value="{{ value_name }}"/>
                    <p class="input-descriptor">{{ _("Location") }}</p>
                    <input type="text" name="location" value="{{ value_info }}"/>
                    <p class="input-descriptor">{{ _("Site Content") }}</p>
                    <textarea id="summernote" name="content">{{ value_content }}</textarea>
                    <p class="input-descriptor">{{ _("Hint") }}</p>
                    <textarea id="summernote-hint" name="hint">{{ value_hint }}</textarea>
                    <p class="input-descriptor">{{ _("Challenge") }}</p>
                    <select name="select_challenge">
                        {% for challenge in challenge_choices %}
                        {% if challenge|string() == preselect|string() %}
                        <option value="{{ challenge }}" selected>{{ challenge }}</option>
                        {% else %}
                        <option value="{{ challenge }}">{{ challenge }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    {% if editing %}
                    <p class="input-descriptor">{{ _("Delete Station") }}</p>
                    <div class="warning">
                        <input name="delete_btn" type="submit" value="{{ _('Delete') }}"/>
                    </div>
                    {% endif %}
                </div>

                <script>
                    $(document).ready(function() {
                        $('#summernote').summernote();
                        $('#summernote-hint').summernote();
                    });
                </script>

                <div class="divider horizontal"></div>

                <div class="button left">
                    <input name="cancel_btn" type="submit" value="{{ _('Cancel') }}"/>
                </div>

                <div class="button right">
                    <input name="save_btn" type="submit" value="{{ _('Save') }}"/>
                </div>
            </form>

            <div class="spacer"></div>
              
        </div>
    </body>
</html>